Just some basic playing with matrices and plots in numpy and matplotlib.

First, some boilerplate to import basics and shorten names. I start pretty much everything with this.

In [2]:
%matplotlib inline
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import numpy.random as rng
np.set_printoptions(precision = 2)

Random matrices are easy, and you can ask any numpy array such as this its shape:

In [3]:
A = rng.random((4,6))
print(A)
print(A.shape)

[[ 0.68  0.18  0.82  0.83  0.93  0.5 ]
 [ 0.32  0.5   0.28  0.03  0.54  0.67]
 [ 0.28  0.61  0.31  0.94  0.55  0.09]
 [ 0.2   0.17  0.93  0.48  0.2   0.32]]
(4, 6)


Think vectors and matrices instead of loops:

In [ ]:
B = 1*(A > 0.25)
print(B)

In [ ]:
# matrix multiplication is a "dot product"
C = rng.random((5,4))
D = np.dot(C,B)
print(D)

Make pictures of it instead of numbers:

In [ ]:
plt.imshow(D, interpolation='nearest', cmap='hot')
plt.colorbar()

In [ ]:
plt.plot(D)

You can "slice" arrays, like this:

In [7]:
print(C)

[[ 0.39  0.08  0.24  0.76]
 [ 0.46  0.63  0.54  0.84]
 [ 0.53  0.37  0.91  0.59]
 [ 0.56  0.29  0.18  0.65]
 [ 0.93  0.43  0.16  0.99]]


In [8]:
print (C[1:3])

[[ 0.46  0.63  0.54  0.84]
 [ 0.53  0.37  0.91  0.59]]


And of course there's stuff like...

In [9]:
print (np.mean(C,axis=1))

[ 0.37  0.62  0.6   0.42  0.63]


In [10]:
from numpy.linalg import inv
D = rng.randint(1,5, size=(4,4))
print (D)
print (inv(D))
print (inv(inv(D)))

[[4 3 1 2]
 [4 1 4 2]
 [2 1 4 2]
 [2 3 4 2]]
[[  1.39e-17   5.00e-01  -5.00e-01   0.00e+00]
 [  0.00e+00   0.00e+00  -5.00e-01   5.00e-01]
 [ -3.33e-01   3.33e-01  -3.33e-01   3.33e-01]
 [  6.67e-01  -1.17e+00   1.92e+00  -9.17e-01]]
[[ 4.  3.  1.  2.]
 [ 4.  1.  4.  2.]
 [ 2.  1.  4.  2.]
 [ 2.  3.  4.  2.]]


### What about some neurons

In [11]:
def sigmoid( phi ):
    y = 1.0/ (1.0 + np.exp(phi))
    return y

In [13]:
x = np.array([1,2,5,3,4])
w = rng.random(x.shape) # just making it the same shape as the input here
phi = np.dot(x, w)
print( sigmoid(phi) )

0.000173645178745


In [15]:
# Or we can do a bunch at once, like a training set...
npats, nins = 10, 5
x = rng.randint(0,2,(npats, nins))  # ie. each row in an input vector
phi = np.dot(x, w)
print (sigmoid(phi))

[ 0.14  0.13  0.21  0.12  0.23  0.07  0.24  0.29  0.13  0.23]


You'll often have to just look at shapes of matrices to get things aligned for dot products:

In [16]:
print(x.shape, w.shape)

(10, 5) (5,)
